name: Update Best Buy Prices

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch: {}      # allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Update prices
        env:
          BESTBUY_API_KEY: ${{ secrets.BESTBUY_API_KEY }}
        run: npm run update:prices

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update Best Buy prices"
          file_pattern: prices.json
